#### read in EEfRT data, loss version. 
### reading text files created by Rfilewriter3 
# see "link file writers.m" in Dropbox/PACO_JS/EFFRT/EFFRT_code for grant

library('stringr')
library('plyr')


##### aggregate loss data ####
outfile <- "EEfRTloss_agg_network_nov_2014.csv"
dataloc <- "EEFRT_data_06302014"
troublesubs <- c(2507,1780 ) #1780 is duplicate file. 2507 output is/was funky
eefrtVersion <- "LOSS"


sys <- Sys.info()['sysname']
if (sys == "Darwin"){
  datafolder <- paste("~/Dropbox/EEfRT for grant/",dataloc,sep="")
  run1loc <- "~/Dropbox/EEfRT for grant/run1.dat"
  run2loc <- "~/Dropbox/EEfRT for grant/run2.dat"
  outdat <- "/Users/Jim/Dropbox/PACO_JS/EEfRT_analysis/"
} else {
  datafolder <- paste("~/My Dropbox/EEfRT for grant/",dataloc,sep="")
  run2loc <- "~/My Dropbox/EEfRT for grant/run2.dat"
  outdat <- "~/My Dropbox/EEfRT for grant"
}


setwd(datafolder)
files<-dir(pattern="*.txt")
files<-files[grep("*LOSS.txt",files)] #hack to avoid first_attempt file..
files<-files[grep("dataStruct*",files)] #only files generated by Rfilewriter

#extract sub numbers
subs<-str_extract(files,"\\d+")
subs<-as.numeric(subs)
subs<-subs[subs>1000] #clean 
subs<-subs[subs<4000]

subs<-subs[!subs %in% troublesubs] ##2507 is a trouble maker.
uberdata<-NULL

for (ii in 1:length(subs)){
  filetouse<-files[grep(subs[ii],files)]
  if(length(filetouse)>0){
    print(subs[ii])
    filename<-paste("./",filetouse,sep="")
    print(filename)
    subdat<- read.delim(filename) 
    if( dim(subdat)[2]==21){
    subdat$subID<-subs[ii]
    subdat$trial<-1:length(subdat$subID)
    uberdata<-rbind(uberdata,subdat)
    } else{
      cat('Suject',subs[ii],'has wrong number of vars, they have',dim(subdat)[2],'\n')
    }
      
  }else      (cat(subs[ii],'nogo','\n'))
  
}

str(uberdata)
if (eefrtVersion== 'LOSS'){
  run <- read.delim(run2loc, header=F)
} else{
  run <- read.delim(run1loc, header=F)
}



str(run)
run$icounter<-1:108
names(run)<-c('prob_color','lossSelect','varAmount','icounter')

udat<-merge(uberdata,run,all.x=TRUE,all.y=FALSE,sort=FALSE)
udat$prob<-.12*as.numeric(udat$prob_color=='b')+.5*as.numeric(udat$prob_color=='y')+.88*as.numeric(udat$prob_color=='r')
udat$expectedvalueHARD<-udat$prob*udat$varAmount  
max(udat$trial)



lossEEFRTmat<-udat
setwd(outdat)
write.csv(lossEEFRTmat,outfile,row.names=F)

